#!/bin/bash
# ============================================================
# ĐỜI SỐNG CÔNG NHÂN VIỆT NAM - ĐẶC BIỆT MIỀN BẮC
# Mức lương & Chi phí sinh hoạt (cập nhật 2026)
# ============================================================

clear
echo "============================================================"
echo "  ĐỜI SỐNG CÔNG NHÂN VIỆT NAM - ĐẶC BIỆT MIỀN BẮC (2026)"
echo "============================================================"
echo ""

echo "1. LƯƠNG TỐI THIỂU VÙNG (từ 01/01/2026 - Nghị định 293/2025/NĐ-CP)"
echo "------------------------------------------------------------"
echo "  Vùng I   (Hà Nội trung tâm, Hải Phòng...): 5.310.000 đ/tháng"
echo "  Vùng II  (ngoại thành Hà Nội, nhiều KCN):  4.730.000 đ/tháng"
echo "  Vùng III                                 : 4.140.000 đ/tháng"
echo "  Vùng IV                                  : 3.700.000 đ/tháng"
echo ""
echo "  → Lương tối thiểu giờ Vùng I: 25.500 đ/giờ"
echo ""

echo "2. LƯƠNG THỰC TẾ CÔNG NHÂN MIỀN BẮC (2026)"
echo "------------------------------------------------------------"
echo "  • Công nhân nhà máy phổ thông     : 7 - 10 triệu đ/tháng"
echo "  • Công nhân kỹ thuật / thợ bậc trung: 10 - 20 triệu đ/tháng"
echo "  • Công nhân xây dựng (thợ phụ)    : 500.000 - 750.000 đ/ngày"
echo "                                    (~13 - 19 triệu/tháng nếu 26 ngày)"
echo "  • Thợ cả / thợ vận hành máy       : 15 - 35 triệu, thậm chí 40-65 triệu"
echo "  • Tổ trưởng / giám sát            : 20 - 47 triệu đ/tháng"
echo ""
echo "  Thu nhập bình quân người lao động:"
echo "  - Đồng bằng sông Hồng (Hà Nội)   : ~9,8 triệu đ/tháng"
echo "  - Thành thị                      : ~10,7 triệu đ/tháng"
echo "  - Cả nước                        : ~9,0 triệu đ/tháng"
echo ""

echo "3. CHI PHÍ SINH HOẠT CÔNG NHÂN TẠI HÀ NỘI / MIỀN BẮC"
echo "------------------------------------------------------------"
echo "  Phòng trọ (công nhân độc thân/nhóm):"
echo "    - Phòng cũ, xuống cấp           : 500.000 - 1.000.000 đ/tháng"
echo "    - Phòng khép kín 15-20m² ven đô : 1.300.000 - 2.500.000 đ/tháng"
echo "    - Phòng tốt hơn / gần trung tâm : 3.500.000 - 4.500.000 đ/tháng"
echo "    (thường chia sẻ 2-4 người)"
echo ""
echo "  Chi phí hàng tháng ước tính (1 người sống tiết kiệm):"
echo "    - Tiền trọ (chia sẻ)            : 1.000.000 - 2.500.000 đ"
echo "    - Ăn uống (tự nấu + cơm công ty): 2.000.000 - 3.000.000 đ"
echo "    - Điện, nước, internet          : 300.000 - 800.000 đ"
echo "    - Xăng xe / đi lại              : 500.000 - 1.000.000 đ"
echo "    - Điện thoại + cá nhân          : 300.000 - 500.000 đ"
echo "    -----------------------------------------------"
echo "    TỔNG ƯỚC TÍNH                   : 4.500.000 - 8.000.000 đ/tháng"
echo ""
echo "  Gia đình 2 vợ chồng + 1-2 con:"
echo "    - Tiền trọ                      : 2.500.000 - 6.000.000 đ"
echo "    - Ăn uống                      : 4.000.000 - 6.000.000 đ"
echo "    - Sữa, bỉm, học phí con        : 1.500.000 - 3.000.000 đ"
echo "    - Điện nước + xăng + khác      : 1.500.000 - 2.500.000 đ"
echo "    -----------------------------------------------"
echo "    TỔNG                            : 10 - 18 triệu đ/tháng"
echo "    (với thu nhập 2 vợ chồng ~16-22 triệu thì rất chật vật)"
echo ""

echo "4. THỰC TRẠNG ĐỜI SỐNG"
echo "------------------------------------------------------------"
echo "  • Nhiều công nhân phải tăng ca mới đủ sống."
echo "  • Phòng trọ chật hẹp, thiếu tiện nghi là phổ biến."
echo "  • Chi phí sinh hoạt Hà Nội cao nhất cả nước."
echo "  • Khoảng 55% lao động cho biết lương vừa đủ chi tiêu cơ bản,"
echo "    26% phải tằn tiện kham khổ (khảo sát 2025)."
echo "  • Nhà ở xã hội cho thuê còn hạn chế, giá vẫn cao với thu nhập."
echo "  • Doanh nghiệp đang nâng lương + đãi ngộ (bao ăn ở, thưởng)"
echo "    để giữ chân lao động, đặc biệt ngành xây dựng & điện tử."
echo ""

echo "5. GHI CHÚ"
echo "------------------------------------------------------------"
echo "  - Dữ liệu tổng hợp từ nguồn công khai 2025-2026"
echo "    (Tổng cục Thống kê, Nghị định 293/2025, báo Lao Động,"
echo "     VnExpress, Talentnet, Livingcost...)"
echo "  - Lương thực tế phụ thuộc tay nghề, tăng ca, phụ cấp,"
echo "    khu vực (KCN Bắc Ninh, Hải Phòng, Hà Nội...)."
echo "  - Có dự thảo đề xuất tăng lương tối thiểu tiếp vào 2027"
echo "    (Vùng I lên ~5,7 triệu)."
echo ""
echo "============================================================"
echo "  Chạy xong. File: doi_song_cong_nhan_mien_bac.sh"
echo "============================================================"
